ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS wc_group VARCHAR(2),
    ADD COLUMN IF NOT EXISTS iso2     VARCHAR(10);

ALTER TABLE matches
    ADD COLUMN IF NOT EXISTS wc_match_id VARCHAR(10),
    ADD COLUMN IF NOT EXISTS matchday    SMALLINT,
    ADD COLUMN IF NOT EXISTS local_date  VARCHAR(30),
    ADD COLUMN IF NOT EXISTS home_name   VARCHAR(100),
    ADD COLUMN IF NOT EXISTS away_name   VARCHAR(100);

CREATE UNIQUE INDEX IF NOT EXISTS matches_wc_id_idx ON matches (wc_match_id);
