ALTER TABLE teams ADD COLUMN IF NOT EXISTS avg_xg_for FLOAT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS avg_xg_updated_at TIMESTAMPTZ;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS avg_xg_source VARCHAR(20);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS avg_xg_match_count INT NOT NULL DEFAULT 0;
